services:
  prometheus:
    image: prom/prometheus:latest
    container_name: unda_prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./monitoring/prometheus/prometheus.yml.example:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus:/etc/prometheus/rules:ro
    ports:
      - '19090:9090'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.5.0
    container_name: unda_grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/idempotency:/var/lib/grafana/dashboards/idempotency:ro
    ports:
      - '13000:3000'
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus-data: {}
  grafana-data: {}
